version: '3.8'

services:
  mongo:
    build: ./infra/mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    build: ./infra/postgres
    container_name: postgres
    environment:
      POSTGRES_DB: avenue_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    build: ./infra/rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  nginx:
    build: ./infra/nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - api-read
      - api-write
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf

  api-read:
    build: ./services/api-read
    container_name: api-read
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: "host=postgres user=user password=password dbname=avenue_db port=5432 sslmode=disable"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"

  api-write:
    build: ./services/api-write
    container_name: api-write
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: "host=postgres user=user password=password dbname=avenue_db port=5432 sslmode=disable"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"

  client-tui:
    build: ./services/client-tui
    container_name: client-tui
    depends_on:
      - api-read
      - api-write
    environment:
      API_READ_URL: "http://api-read:8080"
      API_WRITE_URL: "http://api-write:8080"

volumes:
  mongo_data:
  postgres_data:
